version: '3'
services: # 集合
  docker_nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/cert:/etc/nginx/cert
      # - /home/webserver/html:/usr/share/nginx/html
      - /home/jenkins/jenkins_home/workspace/handsclap_demo/dist:/usr/share/nginx/html
  docker_jenkins:
    user: root # 为了避免一些权限问题 在这我使用了root
    restart: always # 重启方式
    image: jenkinsci/blueocean # 指定服务所使用的镜像 在这里我选择了 LTS (长期支持)
    container_name: jenkins # 容器名称
    ports: # 对外暴露的端口定义
      - 8080:8080
      - 50000:50000

    volumes: # 卷挂载路径
      - /home/jenkins/jenkins_home/:/var/jenkins_home # 这是我们一开始创建的目录挂载到容器内的jenkins_home目录
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker # 这是为了我们可以在容器内使用docker命令
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /home/jenkins/jenkins_home/jks:/var/jenkins_home/jks
    environment:
      JENKINS_ARGS: ' --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/jks/handsclap.cn.jks --httpsKeyStorePassword=8198mqujg88l192'
